apiVersion: v2
name: diffgram
description: A Helm chart for Kubernetes
type: application
version: 1.7.0
appVersion: "1.21.0"

dependencies:
  - name: rabbitmq
    version: 11.2.2
    repository: https://charts.bitnami.com/bitnami
    condition: useRabbitMq